update for v1 release
decred/dexweb pull request #47
Opened 2024-08-20 22:04 UTC by buck54321

This is a rough draft of changes needed for the Bison Wallet v1 release.

What is done
- Direct users towards Bison Wallet, which will temporarily be the only wallet with DCRDEX access
- Temporarily hide Decrediton while we work to get v1-compatible release
- App initialization flow updated to match numerous changes since last edited.

What's not done
- Responsive design checks
- Footer assets and links

This image is what it will look like once Decrediton is ready again. Until then, the Decrediton section will be hidden.

![image](https://github.com/user-attachments/assets/12141f53-2f78-4188-8de1-c5596ed15762)

2024-08-21 09:20 UTC, jholdstock requested changes

2024-08-21 09:20 UTC, jholdstock commented on src/assets/images/get-started3.png
A "New Password" prompt isn't the most compelling choice for the only picture of the UI. Could this stay as a trade window or something a bit more interesting?

2024-08-21 09:20 UTC, jholdstock commented on src/layouts/partials/get-started.html
> +                                Set a new "application password."
```suggestion
                                Set a new "application password".
```

2024-08-21 09:20 UTC, jholdstock commented on src/layouts/partials/get-started.html
> +                        <p>
`<p>` tags need fixing here

2024-08-21 09:20 UTC, jholdstock commented on src/layouts/partials/get-started.html
> +                            The quick configuration dialog will offer you the
Want to add `<p>` tags to these paragraphs?

2024-08-21 09:20 UTC, jholdstock commented on src/layouts/partials/get-started.html
> +                            Navigate to the settings view to connect to a DCRDEX access access trading markets.
```suggestion
                            Navigate to the settings view to connect to a DCRDEX server to access trading markets.
```

2024-08-21 09:20 UTC, jholdstock commented on src/layouts/partials/get-started.html
> +                            Once you are bonded and you have the necessary
`<p>` tags?

2024-08-26 13:01 UTC, buck54321 commented on src/assets/images/bw-logo.png
I started doing this. What if I told you that even after optimizing and running through **svgcleaner**, the file size of the SVG is larger than the PNG?
![image](https://github.com/user-attachments/assets/9bb4a417-5aeb-4a8b-9b21-f6daede9000e)

2024-08-26 15:11 UTC, peterzen commented on src/assets/images/bw-logo.png
It's a complex vector path, hence the beefy SVG.  `svgcleaner` will remove cruft added by design tools but it won't alter the paths.  The additional 8k in the file size isn't really a noticeable difference and it'll render a sharp image on all resolutions whereas the PNG won't.

2024-08-27 09:52 UTC, jholdstock requested changes
I've done a quick pass for mobile responsiveness, please adjust the following in `get-started.scss`

![Screenshot from 2024-08-27 10-51-43](https://github.com/user-attachments/assets/8ddaab8d-ef69-42ba-9855-60a744129d9f)

2024-08-27 09:52 UTC, jholdstock commented on src/layouts/partials/get-started.html
> +                                you want to trade, you'll need to post a bond
```suggestion
                                you want to trade, you'll need to post a bond.
```

2024-08-27 09:52 UTC, jholdstock commented on src/layouts/partials/downloads.html
> +        <img src="{{ $bwlogo.Permalink }}" class="mt-4">
This needs some css for mobile.

Please add `id="bisonlogo"` to the img tag and the following somewhere in `downloads.scss`:

```css
#bisonlogo {
    width: 100%;
    max-width: 441px;
}
```

2024-08-27 09:52 UTC, jholdstock commented on src/layouts/partials/downloads.html
> +        <h4 class="mt-4">Bison Wallet is the official DCRDEX-compatible multi-wallet</h4>
```suggestion
        <p class="mt-4">Bison Wallet is the official DCRDEX-compatible multi-wallet</p>
```

2024-08-28 08:02 UTC, jholdstock approved these changes

2024-08-29 12:09 UTC, buck54321 commented
Looks like we'll have all the options for mac users.
![image](https://github.com/user-attachments/assets/2c6f7dc4-9f38-4eaa-b7e3-90e601a91e59)

2024-09-04 02:43 UTC, buck54321 commented
I think we're good.

2024-09-04 12:52 UTC, merged